title: Pedro Ferreiro  
description: |
  **E-mail:** [pedro.ferreirorega@gmail.com](mailto:pedro.ferreirorega@gmail.com)  
  **LinkedIn:** [pedro-ferreirorega](https://www.linkedin.com/in/pedro-ferreirorega)  
  **Location:** Santiago de Compostela, Spain
theme: jekyll-theme-minimal
logo: "/images/CV_photo.png"

# Navigation links

# Social links
social:
  - name: "GitHub"
    link: "https://github.com/pedro-fr"
  - name: "LinkedIn"
    link: "https://www.linkedin.com/in/pedro-ferreirorega"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
