title: Pedro Ferreiro. # Add a space after the period
description: "An attractive website to showcase my resume"
theme: jekyll-theme-minimal
logo: "/images/CV_photo.png"

# Navigation links

# Social links
social:
  - name: "GitHub"
    link: "https://github.com/pedro-fr"
  - name: "LinkedIn"
    link: "https://www.linkedin.com/in/pedro-ferreirorega"

# Custom settings
author:
  name: "Pedro Ferreiro"
  photo: "/images/CV_photo.png"
  description: "Biotechnology graduate with a keen interest in omics 
  and computational algorithms applicable to biological data."

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag